include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_function_literals_in_foreach_calls: false
    directives_ordering: true
    prefer_single_quotes: true
    sort_pub_dependencies: true

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
