name: esekai
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  const_date_time: ^1.0.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.1.1
  dismissible_page: ^1.0.1
  file_picker: ^5.2.6
  firebase_auth: ^4.4.0
  firebase_core: ^2.9.0
  firebase_database: ^10.1.0
  flex_color_scheme: ^7.0.0-dev.3
  flutter:
    sdk: flutter
  flutter_reorderable_grid_view: ^4.0.0
  flutter_riverpod: ^2.3.2
  flutter_slidable: ^3.0.0
  flutter_speed_dial: ^7.0.0
  flutter_svg: ^2.0.4
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  go_router: ^9.0.3
  google_mlkit_text_recognition: ^0.9.0
  google_sign_in: ^6.0.2
  image_picker: ^1.0.1
  injectable: ^2.1.1
  intl: ^0.18.1
  path_provider: ^2.0.14
  photo_view: ^0.14.0
  printing: ^5.10.3
  riverpod_annotation: ^2.0.2
  simple_icons: ^7.10.0
  syncfusion_flutter_pdf: ^22.1.38
  uuid: ^3.0.7

dev_dependencies:
  build_runner: null
  custom_lint: null
  flutter_lints: ^2.0.0
  flutter_oss_licenses: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  injectable_generator: ^2.1.5
  riverpod_generator: ^2.1.4
  riverpod_lint: ^1.1.6

flutter:
  uses-material-design: true

  assets:
    - assets/images/
